### ISSUE TITLE
Documentation - please clarify what's meant by test/preproduction environment

### ISSUE THREAD

**Issue by rohancragg** [Azure-Samples/azure-ad-conditional-access-apis#11]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

'preproduction environment' is mentioned in this page:
https://github.com/Azure-Samples/azure-ad-conditional-access-apis/blob/main/02-test/readme.md

Please clarify - does this imply two separate AAD directories, one for prod and one for preprod?

**Comment by videor** [comment]
@rohancragg  the recommendation is to have two separate Azure Active Directory tenants. One for pre-production and one for production. This allows you to try out new Conditional Access preview features quickly in pre-production and test out End-to-End experience for end users using test accounts. When you feel ready you can then safely deploy them to your production environment.  Let me know if you have further questions. The diagram below illustrates the lifecycle.

![image](https://user-images.githubusercontent.com/56303396/94170826-729b2900-fe88-11ea-882c-4e05a11ff42e.png)
